defaults: &defaults
    working_directory: /tmp/Statflo/docker-pentahi-di
    shell: /bin/bash --login
    machine:
        enabled: true
        docker_layer_caching: true

version: 2
jobs:
    deploy_to_test:
        <<: *defaults
        steps:
        - checkout
        - run: make setup-circleci
        - run: make ecr-auth
        - run: make build
        - run: make push 

    deploy_to_prod:
        <<: *defaults
        steps:
        - checkout
        - run: make setup-circleci
        - run: make ecr-auth
        - run: make build
        - run: make push VERSION=prod
        - run: make push VERSION=latest

workflows:
    version: 2
    build_and_deploy_to_test:
        jobs:
        - deploy_to_test:
            filters:
              branches:
                only: master
              tags:
                ignore: /.*/

    build_and_deploy_to_prod:
        jobs:
        - deploy_to_prod:
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
